[pytest]
addopts = --browser chrome
base_url =http://localhost:3000/
filterwarnings =
    ignore::DeprecationWarning
markers =
    in_progress: marks tests that are currently in development and should be skipped in standard runs