[pytest]
addopts = --browser chrome
base_url = https://www.serhatozdursun.com
filterwarnings =
    ignore::DeprecationWarning
markers =
    in_progress: marks tests that are currently in development and should be skipped in standard runs
log_cli = true
log_cli_level = INFO