name: UI Automation Test for Firefox

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check if directory exists
        run: |
          if [ ! -d "serhatozdursun-ui-tests" ]; then
            echo "Directory serhatozdursun-ui-tests does not exist!"
            exit 1
          fi
      

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set up Firefox and GeckoDriver
        uses: browser-actions/setup-firefox@latest

      - name: Install Python dependencies
        working-directory: serhatozdursun-ui-tests
        run: |
          pip install -r requirements.txt

      - name: Run tests
        working-directory: serhatozdursun-ui-tests
        id: run_tests
        run: |
          pytest --browser firefox --html=reports/html/report.html --junitxml=reports/report.xml

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: serhatozdursun-ui-tests/reports/html
        continue-on-error: true

      - name: Upload XML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: xml-report
          path: serhatozdursun-ui-tests/reports/report.xml
        continue-on-error: true